### ISSUE TITLE
Mod destroyed my PC

### ISSUE THREAD

**Issue by AForceGaming** [Parik27/V.Rainbomizer#16]
This mod literally destroyed my PC and it won't work at all after it crashed the system
I think the mod is unstable and needs a lot more of fixes because my PC can run the game at stable 60 FPS 
So anyways I played this mod for 2 days before it happened and my last action was closing the game and upon doing that the PC crashed and made a sound that sounds like breaking glass or something like that
At first I didn't panic and waited a few minutes for it to cooldown then hours and now ... Days . 
Yes 6 days passed after this incident and I regret even installing this mod 
Now the PC can't even receive electricity nor boot and I don't understand in hardware but after investigating I think the power supply got burnt and needs replacement
Can't tell you my PC specs because I forgor 👽
Memes aside this mod killed a PC and needs a fix , and I need a new power supply
AForce, RIP PC :'(

**Comment by Numi43** [comment]
Imo your PC just went boom because of the temperature, which deleted the battery basically. Happens.
