### ISSUE TITLE
"The third way" Softlock

### ISSUE THREAD

**Issue by mannyveev** [Parik27/V.Rainbomizer#20]
At the end of "The third way" when you're pushing Weston into the water, you'll have a chance of getting a motorcycle for that part. If you get a motorcycle for it you'll be softlocked from pushing him into the water. The camera will move all around the place and you'll see that the characters fly upward as soon as you start pushing it. You will be softlocked and the camera will stop here:
![image](https://user-images.githubusercontent.com/93378871/139417863-7559656f-15a9-4b80-984b-b8c1e68b9846.png)

**Comment by Fryterp23** [comment]
Keep holding W will most of the time result in a mission pass. If you get stuck, just let go of W for a while and press and hold it again after a few seconds. 
Clips: 
https://streamable.com/jjg1vz
https://streamable.com/41s7sd
