### ISSUE TITLE
Disable Randomizing Player Into Animals [Request]

### ISSUE THREAD

**Issue by ogohogo** [Parik27/V.Rainbomizer#21]
Hey,

It's extremely annoying when Player get's randomized into one of the animals (especially small one's like birds, because it's controls are terrible!). If there would be some value like "RandomizePlayerIntoAnimals" in order to enable or disable it, then that would be great!

**Comment by Parik27** [comment]
Add the animal models to `NSFW_Models.txt` in `rainbomizer/data` and you (or any other ped) won't be randomized into an animal. 

Furthermore, you can add them to `PedsBlacklist.txt` in `rainbomizer/data` (you have to create it) if you don't want animals to be randomized into humans.

https://github.com/Parik27/V.Rainbomizer/blob/master/data/NSFW_Models.txt
