### ISSUE TITLE
Beverly not snapping photos in first Paparazzi mission

### ISSUE THREAD

**Issue by TobiasDiaz1** [Parik27/V.Rainbomizer#23]
Hey there!

So, the title basically says it all. Beverly refuses to take photos of Miranda despite being in the right position. In the two times I had to repeat the mission, this seems to be as a result of using a vehicle that isn't a motorcycle. No softlock occurs, but this makes completing the objective basically impossible. I didn't even know there was special dialogue for getting 0 photos.

**Comment by Fryterp23** [comment]
You can complete the mission without taking pictures. I wouldn't suggest going for all gold medals with rainbomizer installed, because that's pretty much impossible.
