### ISSUE TITLE
my gta

### ISSUE THREAD

**Issue by epicaiden** [Parik27/V.Rainbomizer#24]
when i open gta 5 it keeps crashing after i load in please help

**Comment by pr0gresive** [comment]
https://www.youtube.com/watch?v=L6JMHsopr2M&ab_channel=MasterFlop
i downloaded heapadjuster and the crash was fixed for me

**Comment by SacredGhost** [comment]
I am also having a crash while loading in. Installed a fresh copy and a new mod install.

**Comment by Parik27** [comment]
You should join the Discord server for general support for mod installation. The mod does not normally crash after loading, so it's likely an issue with your game installation or incorrect installation of the mod or its dependencies.
