### ISSUE TITLE
Problem with bury the hatchet 

### ISSUE THREAD

**Issue by aimlessB** [Parik27/V.Rainbomizer#26]
I started from Prolugue with the mod on and the 3rd mission was bury the hatchet. If I get in a vehicle , I cannot exit it again and I even start getting some random damage after a few seconds. I reinstalled the mod and the game, redid my keybinds and failed the mission endless times. It didnt help.

**Comment by VKBOSS** [comment]
For now i would recommend using a taxi to get to your destination and then when you get to north yankton see if you can then exit the car. Some missions in GTA V are coded so you can't get out of the car.
