### ISSUE TITLE
Random Controls stop working

### ISSUE THREAD

**Issue by MrBizzaros** [Parik27/V.Rainbomizer#34]
I'm playing on the Epic Games version. Not sure if it's a feature or a bug but basically sometimes certain controls like pausing the game or getting into vehicles randomly don't work, and I have to restart the game. If it's a feature, I don't know how to turn it off, and if it's a bug, I don't know how to fix it.

**Comment by Parik27** [comment]
It's not a feature.

I'm not sure why this would happen for you since it doesn't for other people that have played the mod. I'd advise checking if you have any other mods that might be conflicting with Rainbomizer or verify your game installation.
