### ISSUE TITLE
Game crashing after a few minutes of playtime

### ISSUE THREAD

**Issue by MrRetr0** [Parik27/V.Rainbomizer#36]
The game constantly crashes after a few minutes of playtime. First happened during the opening credits scene, so after going through the beginning of the game in vanilla, tried playing through Repossession. About 5 minutes in it crashed again. 
This is the only mod I have installed, so it can't be a conflict.

**Comment by Parik27** [comment]
Couple of things you can do to try and see what causes the crash.

- Make sure you don't have any experimental randomizers enabled (currently Handling Randomizer and Switch Scene Randomizer). 
- Also make sure that it doesn't crash without the mod. (It could be a problem with your system).

You should also share your log file (from the day when it crashed). It's located within the logs sub-folder inside the rainbomizer folder in the game directory.

**Comment by MrRetr0** [comment]
> Couple of things you can do to try and see what causes the crash.
> 
> * Make sure you don't have any experimental randomizers enabled (currently Handling Randomizer and Switch Scene Randomizer).
> * Also make sure that it doesn't crash without the mod. (It could be a problem with your system).
> 
> You should also share your log file (from the day when it crashed). It's located within the logs sub-folder inside the rainbomizer folder in the game directory.

I've got the experimental randomizers set to false, and the game runs fine on its own. Here is the log file
[2022-02-28.txt](https://github.com/Parik27/V.Rainbomizer/files/8157052/2022-02-28.txt)
.

**Comment by Parik27** [comment]
Log clearly shows you have other mods installed. It appears there's a conflict with one of your .Net ScriptHook scripts, so I'd advise you to remove that and try again.
