### ISSUE TITLE
Missions randomize even though not configured to do so

### ISSUE THREAD

**Issue by Florianm2907** [Parik27/V.Rainbomizer#40]
So this is the mission randomizer in the config file, same as in the default configuration: 

> [MissionRandomizer]
> 
> Seed = ""
> ForceSeedOnSaves = false
> 
> ForcedMission = "" # All missions will start this instead of a random mission.
> 
> EnableFastSkips = false # Mission skips will be enabled after failing the mission once. Useful for testing

but everytime I start a mission it always starts a random mission.
Cutscene randomizer is turned off btw.

**Comment by ReiDaTecnologia** [comment]
Yeah, they removed the option to disable random missions...
add `MissionRandomizer = false` to disable it

**Comment by mskrzynski** [comment]
This has been fixed in Release v.3.3.1.

**Comment by ReiDaTecnologia** [comment]
yay for that

**Comment by Florianm2907** [comment]
Okay so thanks @ReiDaTecnologia, you fixed my problem
