### ISSUE TITLE
Random Car Spawner

### ISSUE THREAD

**Issue by ViperHush** [Parik27/V.Rainbomizer#47]
Hi, well I'm not actually reporting an issue I just had a question out of curiosity. 
I used this mod few years back and I really enjoyed it. Now I want to install it again and I've been wondering about the expanded and enhanced dlc cars which are not actually present in pc.... Is this  ##mod aware of their absence? So it wouldn't try to spawn them and crash the game?

**Comment by ReiDaTecnologia** [comment]
That issue was fixed long time ago so as long as u use the latest version, u are good
