### ISSUE TITLE
Architect's Plans Approach Screen Bugged

### ISSUE THREAD

**Issue by RainbowShoebill** [Parik27/V.Rainbomizer#49]
When I do the Architect's Plans mission and get to the approach screen my game seems to softlock and doesn't let me choose crew nor approach.

**Comment by Parik27** [comment]
You probably tampered with the Rainbomizer data files (data/Missions.txt). Replace the file and it should work.

**Comment by RainbowShoebill** [comment]
That fixed it. Thank you
